### PR TITLE
Add sssd related paramaters

### PR DESCRIPTION
**Pull request by joshuabaird**
This PR adds several new parameters that allow you to control sudo cache settings for sssd.  It also adds a new class, ipaclient::sssd.

### CODE REVIEW

**Comment by stbenjam** [comment]
Hey thanks! Sorry for the delay, overall it looks OK, I think I want to change the structure of the module a little bit so it's cleaner before I merge this - will try to get to it this week.

**Comment by stbenjam** [comment]
Ah I won't, I'll leave it as is.  Could you add some simple tests for the sssd configuration? The sudo spec should have a good example

**Comment by joshuabaird** [comment]
Ok - I wrote some simple tests.  I'm new to writing rspec tests, so please let me know if I did something stupid.  :)

**Comment by stbenjam** [comment]
New rspec-puppet-augeas was released so running tests

**Pull request closed without merging**
