### PR TITLE
implement --force-join parameter

### PR DESCRIPTION
**Pull request by clecherbauer**
This solves #61

### CODE REVIEW

**Comment by bittner** [comment]
This PR now fixes both issue #61 and the broken build matrix. All tests now pass.

> #61:
> When client is already joined, "ipa-client-install" fails. According to the freeipa project the --force-join option allows to override this limitation.

**Comment by clecherbauer** [comment]
Are there any concerns about merging these changes?

This parameter especially helps to avoid user interaction if you want to reinstall a computer that is already joined in freeIPA. Otherwise you need to delete the machine from freeipa before reinstallation.

**Comment by bittner** [comment]
@joshuabaird @stbenjam Can anyone of you guys merge this PR, or at least comment on it?

Is this project still maintained?

**Comment by joshuabaird** [comment]
Merged. Unfortunately , this module is not maintained as well it should be anymore.  Happy to review and merge any fixes or enhancements though.

**Comment by bittner** [comment]
Yay! :tada:

**Comment by bittner** [comment]
A release on Puppet Forge would be cool. Could you make this happen?

**Pull request merged**
