### PR TITLE
Update to 2.5

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by npwalker** [comment]
@stbenjam is there a reason this hasn't been released yet?  I'd like to see the future parser fixes that have been merged but aren't in a release yet.

**Comment by joshuabaird** [comment]
@npwalker I'm going to take a look and get a new version cut as soon as possible.  What future parser changes are you referring to?

**Comment by npwalker** [comment]
https://github.com/joshuabaird/puppet-ipaclient/commit/5ed15898ed1650d3fa9fb0aeca158f4a19672614

**Comment by joshuabaird** [comment]
Got it - I'll try to cut a new release by tomorrow.  Thanks!

**Comment by joshuabaird** [comment]
@npwalker 2.5 has been released and is available on the forge.

**Pull request closed without merging**
