### PR TITLE
Make code snippets pass puppet-lint

### PR DESCRIPTION
**Pull request by bittner**
- Fixes a few syntax errors and styling issues that puppet-lint would detect.
- Adds the use of the `$::domain` variable and `upcase()` as an example for a generic implementation.

### CODE REVIEW

**Comment by bittner** [comment]
@joshuabaird Can you press the merge button here, too?

**Comment by joshuabaird** [comment]
I’ll take care of this and tag a new Forge release in a bit!

**Comment by bittner** [comment]
@joshuabaird Please press the merge button here! It's just the README. Thank you!

**Comment by joshuabaird** [comment]
My bad.  Merged.

**Comment by bittner** [comment]
Thanks!

A release on Puppet Forge would now be cool. Can you make this happen?

**Comment by joshuabaird** [comment]
Done. 2.5.2 released to Forge.

**Comment by bittner** [comment]
Great! The released module proves to be working fine for a couple of days already. Thanks again!

**Pull request merged**
